import type React from 'react';
import type { AccountSnapshot, AggregatedHolding, AiApiConfig, BuyInput, BuyRecord, Currency, Holding, HoldingNewsItem, HoldingNewsStatus, ImportAuditRecord, PortfolioSummary, QuoteStatus, RiskAlert, RiskAnalysisStatus, SavedSnapshot, SellInput, SellRecord, SnapshotDraft, Tab } from './types';

export type AppContext = {
  tab: Tab;
  setTab: (tab: Tab) => void;
  currency: Currency;
  setCurrency: (currency: Currency) => void;
  masked: boolean;
  setMasked: (masked: boolean) => void;
  uploaded: boolean;
  setUploaded: (uploaded: boolean) => void;
  confirmedRows: Record<string, boolean>;
  setConfirmedRows: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  lastRefresh: string;
  quoteStatus: QuoteStatus;
  refresh: () => Promise<void>;
  holdings: Holding[];
  accountSnapshots: AccountSnapshot[];
  savedSnapshot: SavedSnapshot | null;
  buyRecords: BuyRecord[];
  sellRecords: SellRecord[];
  importLogs: ImportAuditRecord[];
  saveDraftSnapshot: (draft: SnapshotDraft, fileNames: string[]) => void | Promise<void>;
  registerBuy: (input: BuyInput) => Promise<void>;
  revokeBuy: (recordId: string) => Promise<void>;
  registerSell: (holding: Holding, input: SellInput) => Promise<void>;
  revokeSell: (recordId: string) => Promise<void>;
  resetSnapshot: () => void;
  summary: PortfolioSummary;
  aggregated: AggregatedHolding[];
  risks: RiskAlert[];
  riskSummary: string;
  riskAnalysisStatus: RiskAnalysisStatus;
  newsItems: HoldingNewsItem[];
  newsSummary: string;
  newsStatus: HoldingNewsStatus;
  newsFetchedAt: string;
  refreshNews: () => Promise<void>;
  newsAiEnabled: boolean;
  setNewsAiEnabled: (enabled: boolean) => void;
  aiConfig: AiApiConfig;
  setAiConfig: (config: AiApiConfig) => void;
};
